### ISSUE TITLE
Error in CodePipeline when installing pipeline-multienv-gitops pattern -- No stacks match the name(s) eks-blueprint-pipeline-stack

### ISSUE THREAD

**Issue by arvind-v** [aws-samples/cdk-eks-blueprints-patterns#94]
**Describe the bug**

I am trying to install the [Pipeline multi environment pattern](https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/main/docs/patterns/pipeline-multi-env-gitops.md) using the instructions provided.  I get a CodePipeline error in the UpdatePipeline stage after I run the following command:

```
make pattern pipeline-multienv-gitops deploy eks-blueprint-pipeline-stack
```

The error I get is 'No stacks match the name eks-blueprint-pipeline-stack' even though the stack is available in the same account and in the same region.  Here is a snippet of the build logs:
  
```
--
111 | No stacks match the name(s) eks-blueprint-pipeline-stack
112 | [22:22:14] Error: No stacks match the name(s) eks-blueprint-pipeline-stack
113 | at CdkToolkit.validateStacksSelected (/usr/local/lib/node_modules/aws-cdk/lib/index.js:402:3959)
114 | at CdkToolkit.selectStacksForDeploy (/usr/local/lib/node_modules/aws-cdk/lib/index.js:402:2861)
115 | at async CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/index.js:400:146574)
116 | at async exec4 (/usr/local/lib/node_modules/aws-cdk/lib/index.js:455:51970)
117 |  
118 | [Container] 2023/06/06 22:22:14 Command did not exit successfully cdk -a . deploy eks-blueprint-pipeline-stack --require-approval=never --verbose exit status 1
119 | [Container] 2023/06/06 22:22:14 Phase complete: BUILD State: FAILED
120 | [Container] 2023/06/06 22:22:14 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: cdk -a . deploy eks-blueprint-pipeline-stack --require-approval=never --verbose. Reason: exit status 1
```

**To Reproduce**
Follow instructions in README

**Expected behavior**
CloudFormation and CodePipeline stages complete successfully

** Versions **
* node v20.2.0
* npm v9.6.6
* cdk v2.02.0

**Comment by shapirov103** [comment]
We are working on it now.
